### ISSUE TITLE
Too many open files error 

### ISSUE THREAD

**Issue by kohsah** [gawati/gawati-portal-server#1]
File handles are not getting closed after a while -- running the cron service. 

n[13375]: error: error while retrieving filter response Error: getaddrinfo EMFILE localhost:8080
Dec 19 14:07:00 e2e-33-211.e2enetworks.net.in gawati-server-cron[13375]:     at Object._errnoException (util.js:1024:11)
Dec 19 14:07:00 e2e-33-211.e2enetworks.net.in gawati-server-cron[13375]:     at errnoException (dns.js:55:15)
Dec 19 14:07:00 e2e-33-211.e2enetworks.net.in gawati-server-cron[13375]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
Dec 19 14:08:00 e2e-33-211.e2enetworks.net.in gawati-server-cron[13375]: error: error while opening file  Error: EMFILE: too many open files, open 'portal-cache/full-filter-cache.json'
Dec 19 14:08:00 e2e-33-211.e2enetworks.net.in gawati-server-cron[13375]: error: error while opening file  Error: EMFILE: too many open files, open 'portal-cache/full-filter-cache.json'

**Comment by kohsah** [comment]
Switch to bluebird promises based implementation of fs so file handles are automatically closed.
